id: AB44DB2B9
title: 'A River Filled with the Amṛta of Love: A Liturgy for Saving and Releasing
  the Lives of Animals'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:45:53.551766
  last_modified_at: 2022-03-01 00:45:53.551774
